### ISSUE TITLE
Unable to see changes to anything made to template-tags file

### ISSUE THREAD

**Issue by acurcione** [ptbello/_strap#11]
I'm building my first theme using _strap as a base (thank you very much, BTW), but I've run into a snag. I've been trying to modify the post navigation function in template-tags.php which is called out in the functions.php file, but no changes I make there do anything. In fact, I can completely remove the navigation from that file and everything is rendered just fine. I ended up creating a custom function and putting it in the functions file in order to make any edits.

What am I missing here? Shouldn't what's in the template-tags.php be getting used to override the defaults? Or no? Sorry if this is a stupid question, but I'm fairly new to developing at this. Thanks.

**Comment by ptbello** [comment]
Hi @acurcione sorry for the late reply. This is really more of a generic php/WordPress programming question than something specifically related to my code, but I'll do my best.

First of all, you should try and be terribly specific when raising an issue; for instance, you mention
> the post navigation function in template-tags.php

but in that file we have two functions with similar names, `the_posts_navigation()` and `the_post_navigation()`. To avoid any ambiguity, you should mention the exact signature of the function you need help with.

> I can completely remove the navigation from that file and everything is rendered just fine

this can mean either the function does not get called, or that it's output is null. But it doesn't give any information about what you expected the function to do and why.

My best guess here is that you where expecting the output of  `the_posts_navigation()` from `the_post_navigation()` or vice-versa.  
If this doesn't help, you could try stating your question again, more specifically, over at the WordPress forum (you might find something helpful here https://wordpress.org/support/topic/tutorial-on-how-to-use-underscores) or on the http://wordpress.stackexchange.com/
