### ISSUE TITLE
Navbar issues out of the box

### ISSUE THREAD

**Issue by zreese** [ptbello/_strap#14]
So I can reproduce this consistently by just generating a theme using _strap... the nav menu shows up as a long, empty bulleted list. No clue where the menu items are coming from, because changing/deleting the menus has no effect on this block. I've tried this on two fresh local environments.

![image](https://cloud.githubusercontent.com/assets/5454454/9691803/d4de24b8-5312-11e5-8cb7-6909032a3f9a.png)
![image](https://cloud.githubusercontent.com/assets/5454454/9691823/f8adc7c2-5312-11e5-8fce-6b6e3d6822f8.png)

**Comment by Frederic-C** [comment]
same issue there on brand new installed WP + theme

**Comment by ptbello** [comment]
This is due to the default menu not being catered for by _strap, since everyone usually creates their own.
To fix: Create a menu in `Appearance > Menus`, then assign it to the `Primary Menu` theme location.

**Comment by zreese** [comment]
Thanks, that fixed it. Is there a way to change this in _strap so I don't
have to repeat this process in every environment?

**Comment by deviodigital** [comment]
Hope this helps someone :+1:

**Comment by dbonomo** [comment]
I had this issue, but after fixing it by assigning the navigation, the mobile view of the navigation does not expand when clicking the menu button. Trying to track down the issue...

**Comment by ptbello** [comment]
Ok guys, sorry to have kept you waiting - just pushed a [commit](https://github.com/ptbello/_strap/commit/5bc0a75da919fe601f0e4c71f18edadaf18fab3f) that solves this problem.
