### ISSUE TITLE
Using SASS

### ISSUE THREAD

**Issue by girl-elvis** [ptbello/_strap#16]
Hi. I want to use SASS rather than LESS. I notice there is a SASS folder there, but the bootstrap only contains LESS version.
Do you have instructions?

**Comment by deviodigital** [comment]
@ekryski has a pretty nice script on switching from less to sass that you could check out

https://github.com/ekryski/less2sass

**Comment by ptbello** [comment]
Hi @girl-elvis, the SASS folder is there from the original /_s repo (of which it is a fork), and isn't bootstrap-related.
I know Bootstrap 3 does have a [SASS version](https://github.com/twbs/bootstrap-sass) but I wouldn't be able to give you detailed instructions on how to implement it here.
The silver lining is that Bootstrap 4 will be natively SASS, so... stay tuned!
