### ISSUE TITLE
No "Build theme" button

### ISSUE THREAD

**Issue by ghostsquad** [ptbello/_strap#17]
I did exactly as the installation instructions specified, and I never see the "Build theme" button under "Appearance". 

I've tried to upload the _strap-v1.2 zip (from releases) via the Wordpress UI. I've also tried manually FTPing the contents of the zip. I can activate the theme, but the "Build theme" never shows up.

**Comment by ghostsquad** [comment]
I solved this problem by downloading the master branch from: https://github.com/ptbello/_strap/archive/master.zip

Please update your releases! I think it's pretty common to assume that if there are releases, you should use that instead of directly downloading a branch.

**Comment by ptbello** [comment]
Thanks for pointing that out.
That "1.2" release tag was a 2012 leftover from the original repo. I've deleted it now.
