### ISSUE TITLE
Invalid Theme Slug

### ISSUE THREAD

**Issue by ghostsquad** [ptbello/_strap#18]
Weird, I get an error message that my slug is invalid.
```
this-is-a-test is not a valid Theme slug - try: this_is_a_test instead
```
yet the example is:
```
Something like "my-awesome-theme" or "mat"
```

**Comment by ptbello** [comment]
The slug is also used as a prefix in some functions, so it needs to follow function naming constraints.
I corrected the hint accordingly.
Thanks for pointing that out!
