### ISSUE TITLE
Active class on custom post type

### ISSUE THREAD

**Issue by alfredk** [ptbello/_strap#19]
Trying to add active class to custom post type. Doesnt seem to work. I've tried various if  is_singuar(){} and if ( get_post_type() == 'CUSTOM-POST' ) {} and can't figure it out. Any tips or idea how it can be done.

Thanks

**Comment by ptbello** [comment]
Sorry, this is a generic WordPress question, unrelated to this particular theme.
Please refer to the wordpress.org forums on https://wordpress.org/support/

**Comment by pharmak0n** [comment]
check out this page
http://justintadlock.com/archives/2011/07/20/conditional-checks-for-custom-post-types
