### ISSUE TITLE
Problemi con la traduzione italiana

### ISSUE THREAD

**Issue by fciotola** [ptbello/_strap#8]
Ciao Piero ho visto che al template sono allegati i file lingua italiani tradotti da Gavello, ma mi sembra sia una traduzione non completa o sbaglio? i meta data del post "Posted on" e "By" continuano ad esser ein inglese, come posso procedere per evitare questo problema, grazie.

**Comment by ptbello** [comment]
Grazie della segnalazione, ho corretto e ora funziona.
