### ISSUE TITLE
Can you use this as a starter theme to sell on ThemeForest legally?

### ISSUE THREAD

**Issue by chrisdrogaris** [ptbello/_strap#9]

**Comment by ptbello** [comment]
Hi @chrisdrogaris, I'm afraid I'm not very knowledgeable on these matters.
However, _strap is just a fork of [_s](https://github.com/Automattic/_s) that includes [Bootstrap](https://github.com/twbs/bootstrap), so you should probably check their licences:
- For _s: http://www.gnu.org/licenses/gpl-2.0.html
- For Bootstrap: https://github.com/twbs/bootstrap/blob/master/LICENSE
